name: CI

on:
  push:
    paths:
    - '**'
  schedule:
    - cron: "*/15 * * * *"

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        args:
          - "chrome tests/"
          - "firefox tests/"
    steps:
    - uses: actions/checkout@v1
    - name: Run TestCafe
      uses: DevExpress/testcafe-action@latest
      with:
        version: "1.7.1"
        args: $args
